/**
 * Image Gallery feature — view, select, and bulk-download images
 * generated by DALL-E, code interpreter charts, and uploads.
 *
 * Includes:
 *   - Gallery grid overlay with tabs (Images / Charts / Uploads / Public)
 *   - Image card selection with shift-click range select
 *   - Sidebar detail panel (prompt, gen-id, preview conversation)
 *   - Bulk download as ZIP archive (JSZip + FileSaver)
 *   - Image picker dialog for attaching gallery images to prompts
 *   - Share image modal (copy link, X, LinkedIn, Reddit)
 *   - Date-range download, make public, delete operations
 *
 * Original source: content.isolated.end.js lines 9097-9975
 */

import { cachedSettings } from '../isolated-world/settings';
import { closeMenus, downloadFileFromUrl, openUpgradeModal } from '../../utils/shared';
import { isDescendant, addTooltip, toast, showConfirmDialog } from '../isolated-world/ui/primitives';
import { sharePost } from '../isolated-world/api';
import { translate } from './i18n';
import { showDateSelectorDialog } from './export';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Category tabs available in the gallery. */
export type GalleryCategory = 'dalle' | 'chart' | 'upload' | 'public';

/** A gallery image node from the Council API. */
export interface GalleryImageNode {
  image_id: string;
  image?: string;
  download_url?: string;
  prompt?: string;
  title?: string;
  gen_id?: string;
  seed?: string;
  width?: number;
  height?: number;
  category?: string;
  conversation_id?: string;
  created_at?: string | number;
  is_public?: boolean;
  created_by?: { id: string; name?: string };
}

// ---------------------------------------------------------------------------
// Module state
// ---------------------------------------------------------------------------

export let selectedGalleryImage: GalleryImageNode | null = null;
export let allImageNodes: GalleryImageNode[] = [];
let selectedImageGalleryImageIds: string[] = [];
let selectedImagePickerImageIds: string[] = [];
let imageGalleryCurrentTab: GalleryCategory = 'dalle';
let showAll = false;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Format a timestamp into a locale-friendly date string. */
function formatTime(time: unknown): number {
  if (!time) return 0;
  const s = String(time);
  if (s.indexOf('T') !== -1) return new Date(s).getTime();
  if (s.indexOf('.') !== -1 && s.split('.')[0]!.length === 10) return new Date(Number(time) * 1000).getTime();
  if (s.indexOf('.') !== -1 && s.split('.')[0]!.length === 13) return new Date(Number(time)).getTime();
  if (s.length === 13) return new Date(Number(time)).getTime();
  if (s.length === 10) return new Date(Number(time) * 1000).getTime();
  return Number(time);
}

function formatDate(date: Date, showTime = true, longFormat = false): string {
  if (!date) return '';
  const now = new Date();
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);

  const isToday = now.toDateString() === date.toDateString();
  const isYesterday = yesterday.toDateString() === date.toDateString();
  const timeStr = showTime ? ` ${date.toLocaleTimeString('en-US', { hour: 'numeric', minute: 'numeric' })}` : '';

  if (isToday) return `Today${timeStr}`;
  if (isYesterday) return `Yesterday${timeStr}`;
  return `${date.toLocaleDateString('en-US', {
    year: longFormat ? 'numeric' : '2-digit',
    month: longFormat ? 'long' : '2-digit',
    day: '2-digit',
  })}${timeStr}`;
}

function formatDateDalle(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}.${pad(d.getMinutes())}.${pad(d.getSeconds())}`;
}

function isWindows(): boolean {
  return navigator.platform?.toLowerCase().includes('win') ?? false;
}

function dataURItoBlob(dataURI: string): Blob {
  const [header, data] = dataURI.split(',');
  const byteString = atob(data!);
  const buffer = new ArrayBuffer(byteString.length);
  const view = new Uint8Array(buffer);
  for (let i = 0; i < byteString.length; i++) {
    view[i] = byteString.charCodeAt(i);
  }
  return new Blob([buffer], { type: header!.split(':')[1]!.split(';')[0]! });
}

function sanitizeFileName(name: string): string {
  return (name ?? '').replaceAll(' ', '_').replaceAll('/', '-').replaceAll('\\', '-').replaceAll('.', '_');
}

// ---------------------------------------------------------------------------
// ZIP download
// ---------------------------------------------------------------------------

/**
 * Download gallery images as a ZIP file using JSZip.
 *
 * Original: content.isolated.end.js lines 9233-9279
 */
export async function zipImages(
  images: GalleryImageNode[],
  menuButton: HTMLElement | null = null,
  originalButton: HTMLElement | null = null,
  useWebp = true,
): Promise<void> {
  if (images.length === 0) {
    toast('No images to download');
    resetMenuButton(menuButton, originalButton);
    return;
  }

  // Dynamic import to avoid bundling JSZip when not used
  const [{ default: JSZip }, { saveAs }] = await Promise.all([import('jszip'), import('file-saver')]);

  if (menuButton) menuButton.style.width = '100px';

  const zip = new JSZip();
  const folder = zip.folder('Council-Gallery')!;

  for (let i = 0; i < images.length; i++) {
    if (menuButton) menuButton.innerHTML = `${i + 1}/${images.length}`;

    const img = images[i]!;
    const created = new Date(formatTime(img.created_at));
    const dateStr = `${created.getFullYear()}-${created.getMonth() + 1}-${created.getDate()}__${created.getHours()}-${created.getMinutes()}-${created.getSeconds()}`;
    const titleSlug = sanitizeFileName(img.title ?? '');
    const imageUrl = decodeURIComponent(img.image ?? img.download_url ?? '');
    const ext = useWebp ? 'webp' : isWindows() ? 'jpg' : 'png';
    const filename = `${img.conversation_id}/${dateStr}__${img.image_id}${titleSlug ? `__${titleSlug}` : ''}.${ext}`;

    const dataURI: string = await chrome.runtime.sendMessage({
      type: 'downloadImage',
      detail: { url: imageUrl },
    });
    const blob = dataURItoBlob(dataURI);
    folder.file(filename, blob, { binary: true });

    // Also save prompt metadata as .txt
    const txtFilename = `${img.conversation_id}/${dateStr}__${img.image_id}${titleSlug ? `__${titleSlug}` : ''}.txt`;
    const txtContent = `Conversation URL:\nhttps://chatgpt.com/c/${img.conversation_id ?? ''}\n\nTitle:\n${titleSlug}\n\nPrompt:\n${img.prompt ?? ''}`;
    folder.file(txtFilename, txtContent, { binary: false });
  }

  if (menuButton) menuButton.innerHTML = 'Zipping...';

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  saveAs(blob, `${new Date().toISOString().slice(0, 10)}-council-gallery.zip`);
  resetMenuButton(menuButton, originalButton);
}

function resetMenuButton(el: HTMLElement | null, original: HTMLElement | null): void {
  if (el && original) {
    (el as HTMLButtonElement).disabled = false;
    el.style.width = original.style.width;
    el.innerHTML = original.innerHTML;
  }
}

// ---------------------------------------------------------------------------
// Download selected images
// ---------------------------------------------------------------------------

/**
 * Download selected (or all) gallery images via the background worker.
 *
 * Original: content.isolated.end.js lines 9220-9232
 */
export async function downloadSelectedImages(
  menuButton: HTMLElement | null = null,
  imageIds: string[] = [],
  conversationId: string | null = null,
  useWebp = true,
): Promise<void> {
  let originalButton: HTMLElement | null = null;
  if (menuButton) {
    originalButton = menuButton.cloneNode(true) as HTMLElement;
    (menuButton as HTMLButtonElement).disabled = true;
    menuButton.innerHTML =
      '<svg x="0" y="0" viewbox="0 0 40 40" class="spinner icon icon-xl" style="height:24px;"><circle fill="transparent" stroke="#ffffff50" stroke-width="2" stroke-linecap="round" stroke-dasharray="125.6" cx="20" cy="20" r="18"></circle></svg>';
  }

  const images: GalleryImageNode[] = await chrome.runtime.sendMessage({
    type: 'getSelectedGalleryImages',
    detail: {
      category: imageGalleryCurrentTab,
      imageIds,
      conversationId,
    },
  });

  await zipImages(images, menuButton, originalButton, useWebp);
}

// ---------------------------------------------------------------------------
// Make public / delete
// ---------------------------------------------------------------------------

export function makeGalleryImagesPublic(): void {
  const target = selectedImageGalleryImageIds.length === 0 ? 'all' : 'selected';
  showConfirmDialog(
    'Make images public',
    `Are you sure you want to make ${target} images public?`,
    'Cancel',
    'Make public',
    null,
    () => {
      chrome.runtime.sendMessage(
        {
          type: 'shareGalleryImages',
          detail: {
            imageIds: selectedImageGalleryImageIds,
            category: imageGalleryCurrentTab,
          },
        },
        (response) => {
          if (response?.success) {
            toast(
              selectedImageGalleryImageIds.length === 0
                ? 'All images are now public'
                : 'Selected images are now public',
            );
          }
        },
      );
    },
    'green',
  );
}

export function deleteGalleryImages(): void {
  const count = selectedImageGalleryImageIds.length;
  const target = count === 0 ? 'all' : `${count} selected`;
  showConfirmDialog(
    'Delete images',
    `Are you sure you want to delete ${target} images? This cannot be undone.`,
    'Cancel',
    'Delete',
    null,
    () => {
      chrome.runtime.sendMessage(
        {
          type: 'deleteGalleryImages',
          detail: {
            imageIds: selectedImageGalleryImageIds,
            category: imageGalleryCurrentTab,
          },
        },
        (response) => {
          if (response?.success) {
            if (selectedImageGalleryImageIds.length === 0) {
              const list = document.querySelector('#gallery-image-list');
              if (list) list.innerHTML = '';
              resetSidebar();
              toast('All images are deleted');
              return;
            }
            allImageNodes = allImageNodes.filter((n) => !selectedImageGalleryImageIds.includes(n.image_id));
            selectedImageGalleryImageIds.forEach((id) => {
              document.querySelector(`#gallery-image-card-${id}`)?.parentElement?.remove();
            });
            toast('Selected images are deleted');
            const first = document.querySelector<HTMLElement>('img[id^="gallery-image-card-"]');
            first?.click();
            resetGallerySelection();
          }
        },
      );
    },
    'red',
  );
}

// ---------------------------------------------------------------------------
// Selection management
// ---------------------------------------------------------------------------

/**
 * Clear gallery image selection state.
 *
 * Original: content.isolated.end.js lines 9389-9399
 */
export function resetGallerySelection(): void {
  selectedImageGalleryImageIds = [];
  document.querySelectorAll<HTMLElement>('[id^="gallery-image-card-"]').forEach((el) => {
    el.classList.remove('opacity-50');
  });
  document.querySelectorAll<HTMLInputElement>('[id^="image-gallery-checkbox"]').forEach((el) => {
    el.checked = false;
    el.classList.add('invisible');
  });
  const bar = document.querySelector<HTMLElement>('#gallery-selection-bar');
  bar?.classList.add('hidden');
  const count = document.querySelector<HTMLElement>('#gallery-selection-count');
  if (count) count.innerText = '0 selected';
}

// ---------------------------------------------------------------------------
// Image loading
// ---------------------------------------------------------------------------

/**
 * Load a page of images from the backend and render into the gallery grid.
 *
 * Original: content.isolated.end.js lines 9401-9447
 */
export function loadImageList(page = 1, byUserId = ''): void {
  const userId = byUserId || document.querySelector<HTMLElement>('#by-user-id')?.innerText || '';
  const searchInput = document.querySelector<HTMLInputElement>('#gallery-search');
  const searchTerm = searchInput?.value.toLowerCase() ?? '';
  const grid = document.querySelector<HTMLElement>('#gallery-image-list');
  if (!grid) return;

  if (page === 1) {
    grid.innerHTML = `<div class="group relative flex flex-col w-full justify-start items-start gap-2 p-2 cursor-pointer"><div class="relative flex flex-col w-full h-full justify-center items-center gap-2 text-token-text-primary text-2xl font-bold cursor-pointer hover:shadow-xl rounded-xl"><img style="object-fit:none;aspect-ratio:1;background-color: #111;" src="${chrome.runtime.getURL('images/loading.gif')}" class="row-span-4 mx-auto h-full rounded-md object-scale-down"></div></div>`;
  }

  chrome.runtime.sendMessage({ type: 'checkHasSubscription' }, (hasSub) => {
    if (searchTerm && !hasSub) {
      openUpgradeModal();
      return;
    }

    if (page === 1) {
      selectedImageGalleryImageIds = [];
      selectedGalleryImage = null;
    }

    chrome.runtime.sendMessage(
      {
        type: 'getGalleryImages',
        detail: {
          showAll,
          pageNumber: page,
          byUserId: userId,
          category: imageGalleryCurrentTab === 'public' ? 'dalle' : imageGalleryCurrentTab,
          searchTerm,
          isPublic: imageGalleryCurrentTab === 'public',
        },
      },
      (result) => {
        if (!result) return;
        if (page === 1 && result.error) {
          grid.innerHTML = `<div class="flex flex-col w-full justify-start items-start p-2"><div class="relative flex flex-col w-full h-full justify-center items-center gap-2 p-4 text-token-text-primary text-2xl font-bold cursor-pointer bg-token-main-surface-secondary hover:shadow-xl rounded-xl text-center">${result.error}</div></div>`;
          return;
        }

        if (page === 1) allImageNodes.length = 0;
        allImageNodes.push(...(result?.results ?? []));

        if (page === 1 && result?.results?.length > 0) {
          selectedGalleryImage = result.results[0];
        }

        if (allImageNodes.length === 0 && page === 1) {
          grid.innerHTML = `<div class="flex flex-col w-full justify-start items-start p-2"><div class="relative flex flex-col w-full h-full justify-center items-center gap-2 p-4 text-token-text-primary text-2xl font-bold cursor-pointer bg-token-main-surface-secondary hover:shadow-xl rounded-xl text-center">${translate('No images found')}!</div></div>`;
          return;
        }

        // Render image cards
        const cardsHtml = (result?.results ?? [])
          .map(
            (img: GalleryImageNode) =>
              `<div class="group relative flex flex-col w-full justify-start items-start gap-2 p-2 cursor-pointer" style="font-size:12px;" draggable="false">` +
              `<img id="gallery-image-card-${img.image_id}" src="${img.image ?? img.download_url}" alt="${(img.prompt ?? 'Generated by ChatGPT').replace(/[^a-zA-Z0-9 ]/gi, '')}" style="aspect-ratio:1;" class="bg-token-main-surface-tertiary w-full row-span-4 mx-auto h-full rounded-md object-scale-down ${selectedGalleryImage?.image_id === img.image_id ? 'ring-2' : ''} ring-offset-4">` +
              `<div class="invisible absolute start-3 top-3 group-hover:visible"><button id="image-download-button-${img.image_id}" class="flex h-6 w-6 items-center justify-center rounded bg-black/50"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon icon-sm text-token-text-primary"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.70711 10.2929C7.31658 9.90237 6.68342 9.90237 6.29289 10.2929C5.90237 10.6834 5.90237 11.3166 6.29289 11.7071L11.2929 16.7071C11.6834 17.0976 12.3166 17.0976 12.7071 16.7071L17.7071 11.7071C18.0976 11.3166 18.0976 10.6834 17.7071 10.2929C17.3166 9.90237 16.6834 9.90237 16.2929 10.2929L13 13.5858L13 4C13 3.44771 12.5523 3 12 3C11.4477 3 11 3.44771 11 4L11 13.5858L7.70711 10.2929ZM5 19C4.44772 19 4 19.4477 4 20C4 20.5523 4.44772 21 5 21H19C19.5523 21 20 20.5523 20 20C20 19.4477 19.5523 19 19 19L5 19Z" fill="currentColor"></path></svg></button></div>` +
              `<input type="checkbox" id="image-gallery-checkbox-${img.image_id}" class="${selectedImageGalleryImageIds.length === 0 ? 'invisible' : ''} absolute end-3 top-3 ${imageGalleryCurrentTab !== 'public' ? 'group-hover:visible' : ''}" style="z-index: 11; cursor: pointer; border-radius: 2px;">` +
              `</div>`,
          )
          .join('');

        const loadMoreHtml =
          result?.next && hasSub
            ? '<div class="group relative flex flex-col w-full justify-center items-center gap-2 p-2 cursor-pointer"><div id="load-more-images-button" class="relative flex flex-col w-full h-full justify-center items-center gap-2 text-token-text-primary text-2xl font-bold cursor-pointer bg-token-main-surface-secondary hover:shadow-xl rounded-xl">Load more...</div></div>'
            : '';

        const html = cardsHtml + loadMoreHtml;

        if (page === 1) {
          grid.innerHTML = html;
        } else {
          document.querySelector('#load-more-images-button')?.parentElement?.remove();
          grid.insertAdjacentHTML('beforeend', html);
        }

        addGalleryImageCardEventListeners(result.results);
        addLoadMoreImagesEventListener(page);

        if (page === 1) {
          const firstCard = document.querySelector<HTMLElement>(`#gallery-image-card-${allImageNodes[0]?.image_id}`);
          firstCard?.click();
        }
      },
    );
  });
}

// ---------------------------------------------------------------------------
// Load more (infinite scroll)
// ---------------------------------------------------------------------------

function addLoadMoreImagesEventListener(currentPage: number): void {
  const button = document.querySelector<HTMLElement>('#load-more-images-button');
  button?.addEventListener('click', () => {
    button.innerHTML = `<img style="object-fit:none;aspect-ratio:1;background-color: #111;" src="${chrome.runtime.getURL('images/loading.gif')}" class="row-span-4 mx-auto h-full rounded-md object-scale-down">`;
    loadImageList(currentPage + 1);
  });

  if (button) {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            button.click();
            observer.disconnect();
          }
        });
      },
      { threshold: 0.5 },
    );
    observer.observe(button);
  }
}

// ---------------------------------------------------------------------------
// Card event listeners
// ---------------------------------------------------------------------------

/**
 * Attach click, download, and checkbox handlers to gallery image cards.
 *
 * Original: content.isolated.end.js lines 9570-9664
 */
export function addGalleryImageCardEventListeners(images?: GalleryImageNode[]): void {
  if (!images) return;
  const imageIds = images.map((img) => img.image_id);

  // Download buttons
  const downloadBtns = [...document.querySelectorAll<HTMLElement>('[id^="image-download-button-"]')].slice(-24);
  downloadBtns.forEach((btn) => {
    addTooltip(btn, { value: 'Download', position: 'top' });
    const id = btn.id.split('image-download-button-')[1];
    if (!id || !imageIds.includes(id)) return;
    btn.addEventListener('click', (e) => {
      const imgEl = document.querySelector<HTMLImageElement>(`#gallery-image-card-${id}`);
      const ext = (e as MouseEvent).shiftKey ? (isWindows() ? 'jpg' : 'png') : 'webp';
      if (imgEl?.src) downloadFileFromUrl(imgEl.src, `${id}.${ext}`);
    });
  });

  // Share buttons
  const shareBtns = [...document.querySelectorAll<HTMLElement>('[id^="image-share-button-"]')].slice(-24);
  shareBtns.forEach((btn) => {
    addTooltip(btn, { value: 'Share', position: 'top' });
    const id = btn.id.split('image-share-button-')[1];
    if (!id || !imageIds.includes(id)) return;
    btn.addEventListener('click', () => {
      const img = images.find((i) => i.image_id === id);
      if (img) createShareImageModal(img);
    });
  });

  // Checkbox selection
  document.querySelectorAll<HTMLInputElement>('[id^="image-gallery-checkbox"]').forEach((cb) => {
    cb.addEventListener('click', (e) => {
      const id = cb.id.split('image-gallery-checkbox-')[1];
      if (!id || !imageIds.includes(id)) return;

      if (cb.checked && !selectedImageGalleryImageIds.includes(id)) {
        if (selectedImageGalleryImageIds.length === 0) {
          document
            .querySelectorAll<HTMLInputElement>('[id^="image-gallery-checkbox"]')
            .forEach((c) => c.classList.remove('invisible'));
          document.querySelector('#gallery-selection-bar')?.classList.remove('hidden');
        }

        // Shift-click range select
        if ((e as MouseEvent).shiftKey && selectedImageGalleryImageIds.length > 0) {
          const allCards = document.querySelectorAll<HTMLElement>('[id^="gallery-image-card-"]');
          const lastIdx = allImageNodes.findIndex(
            (n) => n.image_id === selectedImageGalleryImageIds[selectedImageGalleryImageIds.length - 1],
          );
          const curIdx = allImageNodes.findIndex((n) => n.image_id === id);
          const minIdx = Math.min(lastIdx, curIdx);
          const maxIdx = Math.max(lastIdx, curIdx);
          for (let i = minIdx; i <= maxIdx; i++) {
            const card = allCards[i];
            if (!card) continue;
            card.classList.add('opacity-50');
            const cardId = card.id.split('gallery-image-card-')[1];
            if (cardId && !selectedImageGalleryImageIds.includes(cardId)) {
              selectedImageGalleryImageIds.push(cardId);
              const checkbox = document.querySelector<HTMLInputElement>(`#image-gallery-checkbox-${cardId}`);
              if (checkbox) checkbox.checked = true;
            }
          }
        } else {
          const card = document.querySelector<HTMLElement>(`#gallery-image-card-${id}`);
          card?.classList.add('opacity-50');
          selectedImageGalleryImageIds.push(id);
        }

        const countEl = document.querySelector<HTMLElement>('#gallery-selection-count');
        if (countEl) countEl.innerText = `${selectedImageGalleryImageIds.length} selected`;
      } else {
        selectedImageGalleryImageIds = selectedImageGalleryImageIds.filter((x) => x !== id);
        const countEl = document.querySelector<HTMLElement>('#gallery-selection-count');
        if (countEl) countEl.innerText = `${selectedImageGalleryImageIds.length} selected`;
        document.querySelector(`#gallery-image-card-${id}`)?.classList.remove('opacity-50');
        if (selectedImageGalleryImageIds.length === 0) resetGallerySelection();
      }
    });
  });

  // Image card click — update sidebar detail
  document.querySelectorAll<HTMLElement>('[id^="gallery-image-card-"]').forEach((card) => {
    const id = card.id.split('gallery-image-card-')[1];
    if (!id || !imageIds.includes(id)) return;
    card.addEventListener('click', () => {
      selectedGalleryImage = images.find((img) => img.image_id === id) ?? null;

      // Highlight selected
      document
        .querySelectorAll<HTMLElement>('[id^="gallery-image-card-"]')
        .forEach((c) => c.classList.remove('ring-2'));
      card.classList.add('ring-2');

      // Update sidebar
      const sidebarImg = document.querySelector<HTMLImageElement>('#gallery-selected-image');
      if (sidebarImg) {
        sidebarImg.src = card.getAttribute('src') ?? '';
        sidebarImg.style.aspectRatio = String(
          Math.min(1, (selectedGalleryImage?.width ?? 1) / (selectedGalleryImage?.height ?? 1)),
        );
      }

      const tsEl = document.querySelector<HTMLElement>('#gallery-selected-image-timestamp');
      if (tsEl && selectedGalleryImage?.created_at) {
        tsEl.textContent = formatDate(new Date(selectedGalleryImage.created_at as string));
      }

      const titleEl = document.querySelector<HTMLElement>('#gallery-selected-image-title');
      const titleWrapper = document.querySelector<HTMLElement>('#gallery-selected-image-title-wrapper');
      if (titleEl) titleEl.textContent = selectedGalleryImage?.title ?? '';
      if (titleWrapper) {
        selectedGalleryImage?.title ? titleWrapper.classList.remove('hidden') : titleWrapper.classList.add('hidden');
      }

      const promptEl = document.querySelector<HTMLElement>('#gallery-selected-image-prompt');
      if (promptEl) {
        promptEl.innerHTML =
          imageGalleryCurrentTab === 'chart'
            ? codeWrapper(selectedGalleryImage?.prompt ?? '')
            : (selectedGalleryImage?.prompt ?? '');
      }

      const genIdEl = document.querySelector<HTMLElement>('#gallery-selected-image-gen-id');
      if (genIdEl) genIdEl.textContent = selectedGalleryImage?.gen_id ?? '';

      const previewBtn = document.querySelector<HTMLElement>('#gallery-preview-conversation-button');
      if (previewBtn) {
        previewBtn.dataset.conversationId = selectedGalleryImage?.conversation_id ?? '';
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Gallery creation
// ---------------------------------------------------------------------------

/**
 * Create and mount the full gallery dialog overlay.
 *
 * Original: content.isolated.end.js lines 9291-9387
 */
export function createImageGallery(): HTMLElement {
  selectedGalleryImage = null;

  const wrapper = document.createElement('div');
  wrapper.id = 'image-gallery';
  wrapper.dataset.state = 'open';
  wrapper.className = 'h-full w-full flex items-center justify-center backdrop-blur-xl';
  wrapper.style.pointerEvents = 'auto';

  wrapper.innerHTML = `
<div role="dialog" data-state="open" class="relative flex h-full w-full justify-stretch divide-x divide-white/10 focus:outline-none" tabindex="-1" style="pointer-events: auto;">
  <div id="image-gallery-image-wrapper" class="flex flex-1 transition-[flex-basis]">
    <div class="flex flex-1 flex-col p-2">
      <div id="gallery-header" class="px-0 pb-4">
        <div class="flex items-center justify-between text-token-text-primary">
          <div class="flex items-center">
            <input type="search" id="gallery-search" tabindex="0" placeholder="${translate('Search gallery')}" class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-sm bg-token-main-surface-secondary me-2">
          </div>
          <div id="gallery-tabs-wrapper" role="radiogroup" class="flex w-full overflow-hidden rounded-xl bg-token-main-surface-tertiary p-1.5 w-max gap-2 flex-shrink-0 self-center" tabindex="0">
            <button id="gallery-tab-dalle" type="button" role="radio" data-state="checked" class="text-md flex-grow rounded-lg border-token-border-medium p-1.5 font-medium text-token-text-tertiary transition hover:text-token-text-primary radix-state-checked:border radix-state-checked:bg-token-main-surface-primary radix-state-checked:text-token-text-primary" tabindex="0">Images</button>
            <button id="gallery-tab-chart" type="button" role="radio" data-state="unchecked" class="text-md flex-grow rounded-lg border-token-border-medium p-1.5 font-medium text-token-text-tertiary transition hover:text-token-text-primary radix-state-checked:border radix-state-checked:bg-token-main-surface-primary radix-state-checked:text-token-text-primary" tabindex="-1">Charts</button>
            <button id="gallery-tab-upload" type="button" role="radio" data-state="unchecked" class="text-md flex-grow rounded-lg border-token-border-medium p-1.5 font-medium text-token-text-tertiary transition hover:text-token-text-primary radix-state-checked:border radix-state-checked:bg-token-main-surface-primary radix-state-checked:text-token-text-primary" tabindex="-1">Uploads</button>
            <button id="gallery-tab-public" type="button" role="radio" data-state="unchecked" class="text-md flex-grow rounded-lg border-token-border-medium p-1.5 font-medium text-token-text-tertiary transition hover:text-token-text-primary radix-state-checked:border radix-state-checked:bg-token-main-surface-primary radix-state-checked:text-token-text-primary" tabindex="-1">Public</button>
          </div>
        </div>
        <div id="gallery-selection-bar" class="hidden flex items-center justify-end py-3 w-full z-10">
          <button id="gallery-selection-cancel-button" class="flex items-center justify-center h-8 rounded-lg px-2 text-token-text-primary border border-token-border-medium me-auto">${translate('Cancel')}</button>
          <span id="gallery-selection-count" class="text-token-text-tertiary text-xs me-4">0 selected</span>
          <button id="gallery-selection-download-button" class="flex items-center justify-center h-8 rounded-lg px-2 text-token-text-primary border border-token-border-medium me-2">${translate('Download')}</button>
        </div>
      </div>
      <div id="gallery-image-list" class="grid grid-cols-1 gap-0.25 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 overflow-y-auto"></div>
    </div>
  </div>
  <div id="image-gallery-sidebar" class="flex overflow-y-auto items-start justify-start overflow-hidden bg-token-sidebar-surface-secondary text-token-text-primary transition-[flex-basis] duration-500">
    <div class="w-[25vw]">
      <div class="flex flex-col w-full justify-start items-start gap-2 p-4" draggable="false">
        <img id="gallery-selected-image" style="aspect-ratio:1;background-color: #111;" src="${chrome.runtime.getURL('images/loading.gif')}" class="row-span-4 mx-auto h-full rounded-md object-scale-down">
        <div id="gallery-selected-image-timestamp" class="w-full text-xs text-token-text-tertiary">...</div>
      </div>
      <div class="flex flex-col items-start gap-3 p-4">
        <span id="gallery-selected-image-title-wrapper" class="w-full flex flex-col items-start gap-3 hidden">
          <div class="text-md text-token-text-primary">Title</div>
          <div id="gallery-selected-image-title" class="w-full text-sm !whitespace-pre-wrap text-token-text-tertiary"></div>
        </span>
        <div class="text-md text-token-text-primary" id="gallery-selected-image-prompt-title">Prompt</div>
        <div id="gallery-selected-image-prompt" class="w-full text-sm !whitespace-pre-wrap text-token-text-tertiary">...</div>
        <div id="gallery-selected-image-gen-id" class="text-xs text-token-text-tertiary"></div>
        <button id="gallery-preview-conversation-button" data-conversation-id="" class="btn relative gap-2 composer-submit-btn composer-submit-button-color">${translate('Preview conversation')}</button>
      </div>
    </div>
  </div>
</div>`;

  return wrapper;
}

// ---------------------------------------------------------------------------
// Gallery tab event listeners
// ---------------------------------------------------------------------------

/**
 * Wire up tab buttons, search, selection bar, and sidebar interactions.
 *
 * Original: content.isolated.end.js lines 9482-9568
 */
export function addImageGalleryEventListeners(): void {
  const searchInput = document.querySelector<HTMLInputElement>('#gallery-search');
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;
  searchInput?.addEventListener('input', () => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      resetSidebar();
      loadImageList();
    }, 300);
  });

  const tabs: [string, GalleryCategory][] = [
    ['#gallery-tab-dalle', 'dalle'],
    ['#gallery-tab-chart', 'chart'],
    ['#gallery-tab-upload', 'upload'],
    ['#gallery-tab-public', 'public'],
  ];

  tabs.forEach(([selector, category]) => {
    document.querySelector(selector)?.addEventListener('click', () => {
      if (imageGalleryCurrentTab === category) return;
      showAll = false;
      imageGalleryCurrentTab = category;

      // Update tab radio states
      tabs.forEach(([sel, cat]) => {
        const btn = document.querySelector<HTMLElement>(sel);
        if (btn) btn.dataset.state = cat === category ? 'checked' : 'unchecked';
      });

      if (searchInput) searchInput.value = '';
      resetSidebar();
      resetGallerySelection();
      loadImageList();
    });
  });

  // Selection bar buttons
  document.querySelector('#gallery-selection-cancel-button')?.addEventListener('click', () => {
    resetGallerySelection();
  });

  const downloadBtn = document.querySelector<HTMLElement>('#gallery-selection-download-button');
  downloadBtn?.addEventListener('click', async (e) => {
    await downloadSelectedImages(downloadBtn, selectedImageGalleryImageIds, null, !(e as MouseEvent).shiftKey);
  });

  // Sidebar prompt copy
  const copyBtn = document.querySelector<HTMLElement>('#gallery-selected-image-prompt-copy-button');
  copyBtn?.addEventListener('click', () => {
    const promptEl = document.querySelector<HTMLElement>('#gallery-selected-image-prompt');
    if (promptEl) {
      navigator.clipboard.writeText(promptEl.textContent ?? '');
      toast('Copied prompt to clipboard');
    }
  });

  // Gen ID copy
  const genIdBtn = document.querySelector<HTMLElement>('#gallery-selected-image-gen-id-copy-button');
  genIdBtn?.addEventListener('click', () => {
    if (genIdBtn) {
      navigator.clipboard.writeText(genIdBtn.innerText);
      toast('Copied Gen ID to clipboard');
    }
  });

  // Preview conversation — navigate to the conversation that produced this image
  const previewBtn = document.querySelector<HTMLElement>('#gallery-preview-conversation-button');
  previewBtn?.addEventListener('click', () => {
    const convId = previewBtn.dataset.conversationId;
    if (!convId) return;
    // Close gallery overlay, then navigate to the conversation
    document.querySelector('#image-gallery')?.remove();
    window.history.pushState({}, '', `/c/${convId}`);
    window.dispatchEvent(new PopStateEvent('popstate', { state: {} }));
  });
}

// ---------------------------------------------------------------------------
// Sidebar reset
// ---------------------------------------------------------------------------

function resetSidebar(): void {
  const img = document.querySelector<HTMLImageElement>('#gallery-selected-image');
  if (img) {
    img.src = chrome.runtime.getURL('images/loading.gif');
    img.style.aspectRatio = '1';
  }
  const ts = document.querySelector<HTMLElement>('#gallery-selected-image-timestamp');
  if (ts) ts.textContent = '...';
  const prompt = document.querySelector<HTMLElement>('#gallery-selected-image-prompt');
  if (prompt) prompt.innerHTML = '...';
  const genId = document.querySelector<HTMLElement>('#gallery-selected-image-gen-id');
  if (genId) genId.textContent = '';
}

// ---------------------------------------------------------------------------
// Code wrapper (for chart tab)
// ---------------------------------------------------------------------------

function codeWrapper(code: string): string {
  if (!code) return '';
  return `<div class="overflow-y-auto" style="background: #333; padding: 8px; border-radius: 8px;"><code class="!whitespace-pre-wrap" style="font-size:12px;">${code}</code></div>`;
}

// ---------------------------------------------------------------------------
// Exported module state accessors (for use by other modules)
// ---------------------------------------------------------------------------

export function getSelectedImageIds(): string[] {
  return selectedImageGalleryImageIds;
}

export function getCurrentTab(): GalleryCategory {
  return imageGalleryCurrentTab;
}

export function getAllImageNodes(): GalleryImageNode[] {
  return allImageNodes;
}

// ---------------------------------------------------------------------------
// Gallery menu (hamburger)
// Original: content.isolated.end.js lines 9096-9172
// ---------------------------------------------------------------------------

/**
 * Return the HTML string for the gallery hamburger menu button.
 *
 * Original: content.isolated.end.js line 9096
 */
export function imageGalleryMenu(): string {
  return `<div id="image-gallery-menu-wrapper" class="me-2" style="min-width:48px;z-index:100;margin-left:56px;"><button id="image-gallery-menu-button" class="${imageGalleryCurrentTab === 'public' ? 'invisible' : ''} relative w-full flex items-center justify-center cursor-pointer rounded-md border bg-token-main-surface-primary border-token-border-medium p-2 text-center focus:border-green-600 focus:outline-none sm:text-sm" type="button">
  <span class="flex items-center justify-center w-full truncate font-semibold text-token-text-primary">
<svg xmlns="http://www.w3.org/2000/svg" stroke="currentColor" fill="currentColor" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" viewBox="0 0 448 512"><path d="M0 88C0 74.75 10.75 64 24 64H424C437.3 64 448 74.75 448 88C448 101.3 437.3 112 424 112H24C10.75 112 0 101.3 0 88zM0 248C0 234.7 10.75 224 24 224H424C437.3 224 448 234.7 448 248C448 261.3 437.3 272 424 272H24C10.75 272 0 261.3 0 248zM424 432H24C10.75 432 0 421.3 0 408C0 394.7 10.75 384 24 384H424C437.3 384 448 394.7 448 408C448 421.3 437.3 432 424 432z"/></svg></span>
</button>
  </div>`;
}

/**
 * Return the HTML string for the gallery menu dropdown options.
 *
 * Original: content.isolated.end.js line 9104
 */
export function imageGalleryMenuOptions(): string {
  const selectedCount = selectedImageGalleryImageIds.length;
  const target = selectedCount > 0 ? 'selected' : 'all';

  return `<ul id="image-gallery-menu-options" style="max-height:400px;width:300px;" class="block transition-all absolute z-10 end-4 mt-1 overflow-auto rounded-2xl text-base focus:outline-none bg-token-main-surface-secondary shadow-long p-1 sm:text-sm -translate-x-1/4" role="menu" aria-orientation="vertical" tabindex="-1">
  ${
    imageGalleryCurrentTab !== 'public'
      ? `
  <li class="relative cursor-pointer select-none rounded-xl py-2 ps-3 pe-9 hover:bg-token-main-surface-tertiary" id="image-gallery-menu-option-download" role="option" tabindex="-1">
  <div class="flex items-center text-token-text-primary">
  <svg stroke="currentColor" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon icon-md me-2"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.70711 10.2929C7.31658 9.90237 6.68342 9.90237 6.29289 10.2929C5.90237 10.6834 5.90237 11.3166 6.29289 11.7071L11.2929 16.7071C11.6834 17.0976 12.3166 17.0976 12.7071 16.7071L17.7071 11.7071C18.0976 11.3166 18.0976 10.6834 17.7071 10.2929C17.3166 9.90237 16.6834 9.90237 16.2929 10.2929L13 13.5858L13 4C13 3.44771 12.5523 3 12 3C11.4477 3 11 3.44771 11 4L11 13.5858L7.70711 10.2929ZM5 19C4.44772 19 4 19.4477 4 20C4 20.5523 4.44772 21 5 21H19C19.5523 21 20 20.5523 20 20C20 19.4477 19.5523 19 19 19L5 19Z" fill="currentColor"></path></svg>
    <span class="font-semibold flex h-6 items-center gap-1 truncate text-token-text-primary">${translate(`Download ${target} images`)}</span>
  </div>
  </li>

  <li class="relative cursor-pointer select-none rounded-xl py-2 ps-3 pe-9 hover:bg-token-main-surface-tertiary" id="image-gallery-menu-option-date-range-download" role="option" tabindex="-1">
  <div class="flex items-center text-token-text-primary">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor" class="icon icon-md me-2"><path d="M96 288C96 270.3 110.3 256 128 256C145.7 256 160 270.3 160 288C160 305.7 145.7 320 128 320C110.3 320 96 305.7 96 288zM320 352C337.7 352 352 366.3 352 384C352 401.7 337.7 416 320 416C302.3 416 288 401.7 288 384C288 366.3 302.3 352 320 352zM192 288C192 274.7 202.7 264 216 264H328C341.3 264 352 274.7 352 288C352 301.3 341.3 312 328 312H216C202.7 312 192 301.3 192 288zM232 360C245.3 360 256 370.7 256 384C256 397.3 245.3 408 232 408H120C106.7 408 96 397.3 96 384C96 370.7 106.7 360 120 360H232zM152 64H296V24C296 10.75 306.7 0 320 0C333.3 0 344 10.75 344 24V64H384C419.3 64 448 92.65 448 128V448C448 483.3 419.3 512 384 512H64C28.65 512 0 483.3 0 448V128C0 92.65 28.65 64 64 64H104V24C104 10.75 114.7 0 128 0C141.3 0 152 10.75 152 24V64zM48 448C48 456.8 55.16 464 64 464H384C392.8 464 400 456.8 400 448V192H48V448z"/></svg>
    <span class="font-semibold flex h-6 items-center gap-1 truncate text-token-text-primary">${translate('Download images by date range')}</span>
  </div>
  </li>

  ${
    imageGalleryCurrentTab === 'dalle'
      ? `
  <li class="relative cursor-pointer select-none rounded-xl py-2 ps-3 pe-9 hover:bg-token-main-surface-tertiary" id="image-gallery-menu-option-public" role="option" tabindex="-1">
  <div class="flex items-center text-token-text-primary">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" stroke="currentColor" fill="currentColor" stroke-width="2" class="icon icon-md me-2" height="1em" width="1em"><path d="M319.9 320c57.41 0 103.1-46.56 103.1-104c0-57.44-46.54-104-103.1-104c-57.41 0-103.1 46.56-103.1 104C215.9 273.4 262.5 320 319.9 320zM369.9 352H270.1C191.6 352 128 411.7 128 485.3C128 500.1 140.7 512 156.4 512h327.2C499.3 512 512 500.1 512 485.3C512 411.7 448.4 352 369.9 352zM512 160c44.18 0 80-35.82 80-80S556.2 0 512 0c-44.18 0-80 35.82-80 80S467.8 160 512 160zM183.9 216c0-5.449 .9824-10.63 1.609-15.91C174.6 194.1 162.6 192 149.9 192H88.08C39.44 192 0 233.8 0 285.3C0 295.6 7.887 304 17.62 304h199.5C196.7 280.2 183.9 249.7 183.9 216zM128 160c44.18 0 80-35.82 80-80S172.2 0 128 0C83.82 0 48 35.82 48 80S83.82 160 128 160zM551.9 192h-61.84c-12.8 0-24.88 3.037-35.86 8.24C454.8 205.5 455.8 210.6 455.8 216c0 33.71-12.78 64.21-33.16 88h199.7C632.1 304 640 295.6 640 285.3C640 233.8 600.6 192 551.9 192z"/></svg>
    <span class="font-semibold flex h-6 items-center gap-1 truncate text-token-text-primary">${translate(`Make ${target} images public`)}</span>
  </div>
  </li>`
      : ''
  }

  <li class="relative text-red-500 cursor-pointer rounded-xl select-none py-2 ps-3 pe-9 hover:bg-token-main-surface-tertiary" id="image-gallery-menu-option-delete" role="option" tabindex="-1">
  <div class="flex items-center">
    <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="icon icon-md me-2" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
    <span class="font-semibold flex h-6 items-center gap-1 truncate text-red-500">${translate(`Delete ${target} images`)}</span>
    </div>
  </li>`
      : ''
  }
  </ul>`;
}

/**
 * Wire up the gallery hamburger menu button and its dropdown options.
 *
 * Original: content.isolated.end.js line 9141
 */
export function addImageGalleryMenuEventListener(): void {
  chrome.runtime.sendMessage({ type: 'checkHasSubscription' }, (hasSub) => {
    const menuBtn = document.querySelector<HTMLButtonElement>('#image-gallery-menu-button');
    if (!menuBtn) return;

    menuBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      e.preventDefault();
      closeMenus();
      const existing = document.querySelector('#image-gallery-menu-options');
      if (existing) {
        existing.remove();
        return;
      }
      menuBtn.insertAdjacentHTML('afterend', imageGalleryMenuOptions());
    });

    // Close on outside click
    document.body.addEventListener('click', (ev) => {
      const opts = document.querySelector('#image-gallery-menu-options');
      if (
        opts &&
        !(opts as HTMLElement).contains(ev.target as Node) &&
        !(menuBtn as HTMLElement).contains(ev.target as Node)
      ) {
        opts.remove();
      }
    });

    // Option click handlers
    document.body.addEventListener('click', async (ev) => {
      const target = (ev.target as HTMLElement).closest('[id^="image-gallery-menu-option-"]');
      if (!target) return;

      document.querySelector('#image-gallery-menu-options')?.remove();
      const action = target.id.split('image-gallery-menu-option-')[1];

      if (!hasSub) {
        openUpgradeModal();
        return;
      }

      if (action === 'download') {
        await downloadSelectedImages(menuBtn, selectedImageGalleryImageIds, null, !ev.shiftKey);
      }

      if (action === 'date-range-download') {
        showDateSelectorDialog(
          'Download Images',
          'Select date range',
          'Cancel',
          'Download',
          null,
          async (startDate, endDate) => {
            chrome.runtime.sendMessage(
              {
                type: 'getGalleryImagesByDateRange',
                detail: { category: imageGalleryCurrentTab, startDate, endDate },
              },
              async (images) => {
                await zipImages(images, menuBtn, menuBtn.cloneNode(true) as HTMLElement, !ev.shiftKey);
              },
            );
          },
          'green',
          true,
        );
      }

      if (action === 'public') {
        makeGalleryImagesPublic();
      }

      if (action === 'delete') {
        deleteGalleryImages();
      }
    });
  });
}

// ---------------------------------------------------------------------------
// loadMissingImages
// Original: content.isolated.end.js line 9449
// ---------------------------------------------------------------------------

/**
 * Fetch download URLs for images that are missing their image blob,
 * update the card src in the DOM, and upload them to the backend.
 */
export function loadMissingImages(images: GalleryImageNode[]): void {
  images?.forEach(async (img) => {
    if (img.image) return;

    // If we already have a local download URL, use it directly
    if (img.download_url && img.download_url.includes('localhost')) {
      const card =
        document.querySelector(`#gallery-image-card-${img.image_id}`) ||
        document.querySelector(`#image-picker-image-card-${img.image_id}`);
      if (card) (card as HTMLImageElement).src = img.download_url;
      return;
    }

    chrome.runtime.sendMessage(
      {
        type: 'getDownloadUrlFromFileId',
        detail: { conversationId: img.conversation_id, fileId: img.image_id },
      },
      (resp: any) => {
        if (!resp?.download_url) return;
        const card =
          document.querySelector(`#gallery-image-card-${img.image_id}`) ||
          document.querySelector(`#image-picker-image-card-${img.image_id}`);
        if (card) (card as HTMLImageElement).src = resp.download_url;

        // Upload to backend for persistent storage
        chrome.runtime.sendMessage({
          type: 'downloadAndUploadImages',
          detail: {
            images: [{ fileId: img.image_id, fileName: resp.file_name, downloadUrl: resp.download_url }],
          },
        });
      },
    );
  });
}

// ---------------------------------------------------------------------------
// dalleImageEventListener
// Original: content.isolated.end.js line 10257
// ---------------------------------------------------------------------------

/**
 * Add click and download listeners for DALL-E image elements within a
 * message. Clicking opens/reuses the DALL-E editor; download button
 * saves the image directly.
 *
 * @param allImages All image elements in the message
 * @param imgEl     The specific image element
 * @param messageId The parent message ID
 * @param index     Image index within the message
 */
export function dalleImageEventListener(
  allImages: HTMLImageElement[],
  imgEl: HTMLImageElement,
  messageId: string,
  index: number,
): void {
  imgEl.addEventListener('click', (ev) => {
    ev.stopPropagation();

    // Cancel any existing edit mode
    const cancelBtn = document.querySelector<HTMLElement>('#dalle-editor-edit-mode-cancel-button');
    cancelBtn?.click();

    const editor = document.querySelector('#dalle-editor');

    // Remove old overlay, add new one
    document.querySelector('#dalle-dark-image-overlay')?.remove();
    imgEl.parentElement?.insertAdjacentHTML(
      'beforeend',
      '<div id="dalle-dark-image-overlay" class="pointer-events-none absolute inset-0 shadow-[inset_0_0_0_1px_rgba(0,0,0,0.1)] dark:shadow-[inset_0_0_0_1px_rgba(255,255,255,0.1)] bg-black/50 group-hover:bg-black/70"></div>',
    );

    if (!editor) {
      toast('DALL-E image editor coming soon', 'warning');
      return;
    }

    // Update existing editor
    document.querySelector('#dalle-editor-info-menu')?.remove();
    const centerImg = editor.querySelector<HTMLImageElement>('#dalle-editor-center-image');
    if (centerImg) {
      centerImg.src = imgEl.src;
      centerImg.alt = imgEl.alt;
      centerImg.width = imgEl.naturalWidth;
      centerImg.height = imgEl.naturalHeight;
      centerImg.dataset.fileId = imgEl.dataset.fileId ?? '';
      centerImg.dataset.genId = imgEl.dataset.genId ?? '';
    }

    // Update navigation
    const nav = editor.querySelector<HTMLElement>('#dalle-editor-navigation');
    if (nav) {
      nav.dataset.messageId = messageId;
      if (allImages.length === 1) {
        nav.classList.replace('visible', 'invisible');
      } else {
        nav.classList.replace('invisible', 'visible');
        const curIdx = editor.querySelector('#dalle-editor-nav-cur-index');
        const total = editor.querySelector('#dalle-editor-nav-total');
        if (curIdx) curIdx.textContent = String(index + 1);
        if (total) total.textContent = String(allImages.length);
        const prevBtn = editor.querySelector<HTMLButtonElement>('#dalle-editor-prev-image');
        const nextBtn = editor.querySelector<HTMLButtonElement>('#dalle-editor-next-image');
        if (prevBtn) prevBtn.disabled = index === 0;
        if (nextBtn) nextBtn.disabled = index === allImages.length - 1;
      }
    }
  });

  // Download button
  const dlBtn = imgEl.parentElement?.querySelector(`#dalle-image-download-button-${messageId}-${index}`);
  dlBtn?.addEventListener('click', (ev) => {
    ev.stopPropagation();
    const filename = `DALL\u00B7E ${formatDateDalle()} - ${imgEl.alt}.webp`;
    // Download using fetch + blob pattern
    fetch(imgEl.src)
      .then((r) => r.blob())
      .then((blob) => {
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = filename;
        a.click();
        URL.revokeObjectURL(a.href);
      })
      .catch(() => toast('Failed to download image', 'error'));
  });

  // Info/copy gen-id on parent click
  const infoEl = imgEl.parentElement?.querySelector(`#dalle-image-info-${messageId}-${index}`);
  if (infoEl) {
    imgEl.parentElement?.addEventListener('click', (ev) => {
      ev.stopPropagation();
      if (ev.shiftKey) {
        const seedEl = imgEl.parentElement?.querySelector(`#dalle-image-seed-${messageId}-${index}`);
        if (seedEl) {
          navigator.clipboard.writeText(seedEl.textContent ?? '');
          toast('Copied Seed to clipboard');
        }
      } else {
        const genIdEl = imgEl.parentElement?.querySelector(`#dalle-image-gen-id-${messageId}-${index}`);
        if (genIdEl) {
          navigator.clipboard.writeText(genIdEl.textContent ?? '');
          toast('Copied Gen ID to clipboard');
        }
      }
    });
  }
}

// ---------------------------------------------------------------------------
// User filter chip
// Original: content.isolated.end.js line 9666
// ---------------------------------------------------------------------------

/** Remove existing gallery user filter chip. */
function removeUserFilter(): void {
  document.querySelector('#gallery-filter')?.remove();
}

/**
 * Add a user filter chip above the gallery grid.
 *
 * Original: content.isolated.end.js line 9666
 */
export function addUserFilter(user: { id?: string }): void {
  removeUserFilter();
  const header = document.querySelector('#gallery-header');
  if (!header) return;
  const chip = document.createElement('div');
  chip.id = 'gallery-filter';
  chip.className = 'flex items-center justify-between py-2 text-token-text-primary';
  chip.innerHTML = `<div class="flex items-center gap-2 py-1 px-3 border border-token-border-medium rounded-full"><div class="text-xs">Images by user id: <span id="by-user-id">${user?.id ?? ''}</span></div><button id="remove-filter-button" class="transition text-token-text-tertiary hover:text-token-text-primary" aria-label="remove filter" type="button"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="icon icon-md" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button></div>`;
  header.insertAdjacentElement('afterend', chip);
  document.querySelector('#remove-filter-button')?.addEventListener('click', () => {
    removeUserFilter();
    loadImageList();
  });
}

// ---------------------------------------------------------------------------
// Image picker dialog
// Original: content.isolated.end.js lines 9707-9843
// ---------------------------------------------------------------------------

/**
 * Open the image picker dialog (select gallery images to attach to input).
 *
 * Original: content.isolated.end.js line 9707
 */
export function showImagePicker(): void {
  selectedImagePickerImageIds = [];
  const skeletonCards = Array.from({ length: 20 })
    .map(
      () =>
        '<div class="relative flex flex-col justify-start items-start gap-2 p-2 cursor-pointer" draggable="false"><div style="aspect-ratio:1;" class="bg-token-main-surface-primary w-full row-span-4 mx-auto h-full rounded-md object-scale-down"></div></div>',
    )
    .join('');

  const html = `<div data-state="open" class="fixed inset-0 bg-black/50" style="pointer-events: auto;">
    <div class="h-full w-full grid grid-cols-[10px_1fr_10px] grid-rows-[minmax(10px,1fr)_auto_minmax(10px,1fr)] md:grid-rows-[minmax(20px,1fr)_auto_minmax(20px,1fr)] overflow-y-auto">
      <div id="image-picker-dialog-content" role="dialog" data-state="open" class="relative col-auto col-start-2 row-auto row-start-2 w-full rounded-xl text-start shadow-xl transition-all start-1/2 ltr:-translate-x-1/2 rtl:translate-x-1/2 bg-token-main-surface-secondary max-w-xl border-token-border-medium border" tabindex="-1" style="pointer-events: auto; width: 700px; max-width: 90vw; height: 500px; max-height: 90vh;">
        <div class="px-4 pb-4 pt-5 flex items-center justify-between border-b border-token-border-medium">
          <div class="flex"><div class="flex items-center"><div class="flex grow flex-col gap-1"><h2 class="text-lg font-medium leading-6 text-token-text-primary">${translate('Select images')}</h2></div></div></div>
        </div>
        <div class="p-4 flex flex-col overflow-hidden" style="height: calc(100% - 60px);">
          <div id="image-picker-image-list" class="grid grid-cols-5 content-start w-full h-full auto-rows-min text-xs text-token-text-primary overflow-y-auto rounded-md">${skeletonCards}</div>
          <div class="mt-5 flex justify-between">
            <div style="display: flex; justify-content: flex-start; align-items: center;">
              <span id="image-picker-selection-count" class="text-sm text-token-text-tertiary">0 selected</span>
            </div>
            <div class="flex flex-row-reverse gap-3 ms-auto">
              <button disabled id="confirm-button" class="btn relative btn-success text-white"><div class="flex w-full gap-2 items-center justify-center">${translate('Attach')}</div></button>
              <button id="cancel-button" class="btn relative btn-secondary"><div class="flex w-full gap-2 items-center justify-center">${translate('Cancel')}</div></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>`;

  const wrapper = document.createElement('div');
  wrapper.id = 'image-picker-dialog';
  wrapper.className = 'absolute inset-0';
  wrapper.style.cssText = 'z-index: 100101;';
  wrapper.innerHTML = html;
  document.body.appendChild(wrapper);

  const confirmBtn = wrapper.querySelector('#confirm-button') as HTMLElement;
  const cancelBtn = wrapper.querySelector('#cancel-button') as HTMLElement;

  confirmBtn.addEventListener('click', async (ev) => {
    ev.preventDefault();
    ev.stopPropagation();
    closeMenus();
    const checked = Array.from(
      document.querySelectorAll<HTMLInputElement>('[id^="image-picker-checkbox"]:checked'),
    ).map((cb) => ({
      imageId: cb.id.split('image-picker-checkbox-')[1]!,
      imageUrl:
        (
          document.querySelector(
            `#image-picker-image-card-${cb.id.split('image-picker-checkbox-')[1]}`,
          ) as HTMLImageElement
        )?.src ?? '',
    }));
    if (checked.length === 0) {
      toast('No images selected', 'error');
      return;
    }
    const { attachImagesToInput } = await import('./speech');
    await attachImagesToInput(checked);
    wrapper.remove();
  });

  cancelBtn.addEventListener('click', (ev) => {
    ev.preventDefault();
    ev.stopPropagation();
    closeMenus();
    wrapper.remove();
  });

  wrapper.addEventListener('click', (ev) => {
    if ((confirmBtn as any).querySelector('#progress-spinner')) return;
    const content = document.querySelector('#image-picker-dialog-content') as HTMLElement;
    if (!isDescendant(content, ev.target as HTMLElement)) wrapper.remove();
  });

  getImagesForPage(1);
}

/**
 * Fetch a page of gallery images and render into the image picker.
 *
 * Original: content.isolated.end.js line 9766
 */
async function getImagesForPage(page: number): Promise<void> {
  const list = document.querySelector('#image-picker-image-list');
  if (!list) return;

  const result = await chrome.runtime.sendMessage({
    type: 'getGalleryImages',
    detail: { pageNumber: page, category: 'all', searchTerm: '' },
  });
  if (!result?.results?.length) return;

  const hasNext = result.next;
  const cardsHtml = result.results
    .map(
      (img: GalleryImageNode) =>
        `<div class="group relative flex flex-col justify-start items-start gap-2 p-2 cursor-pointer" draggable="false"><img id="image-picker-image-card-${img.image_id}" src="${img.image || img.download_url}" alt="${(img.prompt ?? 'Generated by ChatGPT').replace(/[^a-zA-Z0-9 ]/gi, '')}" style="aspect-ratio:1;" class="bg-token-main-surface-primary border border-token-border-medium w-full row-span-4 mx-auto h-full rounded-md object-scale-down"><input type="checkbox" id="image-picker-checkbox-${img.image_id}" class="${selectedImagePickerImageIds.length === 0 ? 'invisible' : ''} absolute end-3 top-3 group-hover:visible" style="z-index: 11; cursor: pointer; border-radius: 2px;"></div>`,
    )
    .join('');

  if (page === 1) {
    list.innerHTML = cardsHtml;
  } else {
    document.querySelector('#load-more-images-button')?.parentElement?.remove();
    list.insertAdjacentHTML('beforeend', cardsHtml);
  }

  if (hasNext) {
    list.insertAdjacentHTML(
      'beforeend',
      '<div class="flex flex-col w-full justify-start items-start gap-2 p-2 w-full" style="aspect-ratio:1;"><div id="load-more-images-button" class="relative flex flex-col w-full h-full justify-center items-center text-token-text-primary text-2xl font-bold cursor-pointer bg-token-main-surface-secondary hover:shadow-xl rounded-xl">Load more...</div></div>',
    );
  }

  loadMissingImages(result.results);
  addImagePickerEventListeners(result.results, page);
}

/**
 * Attach event listeners to image picker cards, checkboxes, and load-more.
 *
 * Original: content.isolated.end.js line 9784
 */
function addImagePickerEventListeners(images: GalleryImageNode[], page: number): void {
  const imageIds = images.map((img) => img.image_id);

  // Click on image card → toggle checkbox
  document.querySelectorAll<HTMLElement>('[id^="image-picker-image-card"]').forEach((card) => {
    const id = card.id.split('image-picker-image-card-')[1];
    if (id && imageIds.includes(id)) {
      card.addEventListener('click', () => {
        const cb = document.querySelector(`#image-picker-checkbox-${id}`) as HTMLInputElement | null;
        cb?.click();
      });
    }
  });

  // Checkbox change → track selection
  document.querySelectorAll<HTMLInputElement>('[id^="image-picker-checkbox"]').forEach((cb) => {
    cb.addEventListener('click', (ev) => {
      ev.stopPropagation();
      if (selectedImagePickerImageIds.length >= 10 && cb.checked) {
        ev.preventDefault();
        toast('Maximum 10 images can be selected', 'error');
        return;
      }

      const id = cb.id.split('image-picker-checkbox-')[1]!;
      if (!imageIds.includes(id)) return;

      if (cb.checked && !selectedImagePickerImageIds.includes(id)) {
        const confirmBtn = document.querySelector('#image-picker-dialog #confirm-button') as HTMLButtonElement;
        if (confirmBtn) confirmBtn.disabled = false;
        if (selectedImagePickerImageIds.length === 0) {
          document.querySelectorAll('[id^="image-picker-checkbox"]').forEach((c) => c.classList.remove('invisible'));
        }
        const imgCard = document.querySelector(`#image-picker-image-card-${id}`) as HTMLElement | null;
        imgCard?.classList.add('opacity-50');
        selectedImagePickerImageIds.push(id);
        const count = document.querySelector('#image-picker-selection-count');
        if (count) count.textContent = `${selectedImagePickerImageIds.length} selected`;
      } else {
        selectedImagePickerImageIds = selectedImagePickerImageIds.filter((s) => s !== id);
        const count = document.querySelector('#image-picker-selection-count');
        if (count) count.textContent = `${selectedImagePickerImageIds.length} selected`;
        const imgCard = document.querySelector(`#image-picker-image-card-${id}`) as HTMLElement | null;
        imgCard?.classList.remove('opacity-50');
        if (selectedImagePickerImageIds.length === 0) resetImagePickerSelection();
      }
    });
  });

  // Load more button
  const loadMoreBtn = document.querySelector('#load-more-images-button') as HTMLElement | null;
  loadMoreBtn?.addEventListener('click', () => {
    loadMoreBtn.innerHTML = `<img style="object-fit:none;aspect-ratio:1;background-color: #111;" src="${chrome.runtime.getURL('images/loading.gif')}" class="row-span-4 mx-auto h-full rounded-md object-scale-down">`;
    getImagesForPage(page + 1);
  });

  // IntersectionObserver for auto-load
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          loadMoreBtn?.click();
          observer.disconnect();
        }
      });
    },
    { threshold: 0.5 },
  );
  if (loadMoreBtn) observer.observe(loadMoreBtn);
}

/**
 * Reset image picker selection state (uncheck all, disable confirm).
 *
 * Original: content.isolated.end.js line 9834
 */
function resetImagePickerSelection(): void {
  const confirmBtn = document.querySelector('#image-picker-dialog #confirm-button') as HTMLButtonElement | null;
  if (confirmBtn) confirmBtn.disabled = true;
  document.querySelectorAll<HTMLElement>('[id^="image-picker-image-card-"]').forEach((el) => {
    el.classList.remove('opacity-50');
  });
  document.querySelectorAll<HTMLInputElement>('[id^="image-picker-checkbox"]').forEach((cb) => {
    cb.checked = false;
    cb.classList.add('invisible');
  });
  const count = document.querySelector('#image-picker-selection-count');
  if (count) count.textContent = '0 selected';
}

// ---------------------------------------------------------------------------
// Share image modal
// Original: content.isolated.end.js lines 9845-9975
// ---------------------------------------------------------------------------

/**
 * Create and show a share image modal with social sharing buttons.
 *
 * Original: content.isolated.end.js line 9845
 */
export function createShareImageModal(image: GalleryImageNode & { conversation_id?: string }): void {
  const title = image.title || image.prompt || 'Untitled';
  const imgSrc = image.image || image.download_url || '';

  const html = `<div id="share-image-modal-content" class="fixed inset-0" data-state="open" style="pointer-events: auto; backdrop-filter: blur(4px); background-color: rgba(0, 0, 0, 0.8); z-index: 100000;">
    <div class="z-50 h-full w-full overflow-y-auto grid grid-cols-[10px_1fr_10px] grid-rows-[minmax(10px,1fr)_auto_minmax(10px,1fr)] md:grid-rows-[minmax(20px,1fr)_auto_minmax(20px,1fr)]" style="opacity: 1; transform: none;">
      <div id="share-image-modal-dialog" role="dialog" data-state="open" class="popover bg-token-sidebar-surface relative start-1/2 col-auto col-start-2 row-auto row-start-2 h-full w-full gap-4 p-4 text-start ltr:-translate-x-1/2 rtl:translate-x-1/2 dark:bg-[#171717] rounded-[36px] shadow-[0_32px_48px_rgba(0,0,0,0.175),_0_0_1px_rgba(0,0,0,0.2)] dark:shadow-[0_32px_48px_rgba(0,0,0,0.175),_0_0_1px_rgba(255,255,255,0.4)] flex flex-col pb-4 focus:outline-hidden max-w-[640px]" tabindex="-1" style="pointer-events: auto;">
        <div class="px-4 pb-2 sm:p-6 flex items-center justify-between border-b border-black/10 dark:border-white/10">
          <h2 id="share-image-title" class="text-token-text-primary text-3xl leading-6 font-semibold tracking-tight max-sm:text-xl">${escapeHTMLLocal(title)}</h2>
          <button id="share-image-close-button" class="hover:bg-token-main-surface-secondary flex h-8 w-8 items-center justify-center rounded-full bg-transparent" aria-label="Close" type="button">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon icon-md"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.63603 5.63604C6.02656 5.24552 6.65972 5.24552 7.05025 5.63604L12 10.5858L16.9497 5.63604C17.3403 5.24552 17.9734 5.24552 18.364 5.63604C18.7545 6.02657 18.7545 6.65973 18.364 7.05025L13.4142 12L18.364 16.9497C18.7545 17.3403 18.7545 17.9734 18.364 18.364C17.9734 18.7545 17.3403 18.7545 16.9497 18.364L12 13.4142L7.05025 18.364C6.65972 18.7545 6.02656 18.7545 5.63603 18.364C5.24551 17.9734 5.24551 17.3403 5.63603 16.9497L10.5858 12L5.63603 7.05025C5.24551 6.65973 5.24551 6.02657 5.63603 5.63604Z" fill="currentColor"></path></svg>
          </button>
        </div>
        <div>
          <div class="max-xs:max-h-[260px] flex h-[30vh] max-h-[550px] max-w-full justify-center rounded-xl max-sm:max-h-[300px]">
            <img class="rounded-xl" alt="${escapeHTMLLocal(title)}" src="${imgSrc}">
          </div>
          <div class="mt-12 flex flex-wrap justify-center space-y-4 space-x-12 max-sm:mt-6 max-sm:space-x-6">
            <button id="share-image-copy-link" class="relative flex flex-col gap-y-4 disabled:opacity-50 max-sm:gap-y-2">
              <div class="shadow-token-border-default flex h-16 w-16 items-center justify-center rounded-full shadow-md max-sm:h-12 max-sm:w-12">
                <div class="pointer-events-none flex h-8 w-8 items-center justify-center max-sm:h-6 max-sm:w-6">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M18.2929 5.70711C16.4743 3.88849 13.5257 3.88849 11.7071 5.7071L10.7071 6.70711C10.3166 7.09763 9.68341 7.09763 9.29289 6.70711C8.90236 6.31658 8.90236 5.68342 9.29289 5.29289L10.2929 4.29289C12.8926 1.69323 17.1074 1.69323 19.7071 4.29289C22.3068 6.89256 22.3068 11.1074 19.7071 13.7071L18.7071 14.7071C18.3166 15.0976 17.6834 15.0976 17.2929 14.7071C16.9024 14.3166 16.9024 13.6834 17.2929 13.2929L18.2929 12.2929C20.1115 10.4743 20.1115 7.52572 18.2929 5.70711ZM15.7071 8.29289C16.0976 8.68342 16.0976 9.31658 15.7071 9.70711L9.7071 15.7071C9.31658 16.0976 8.68341 16.0976 8.29289 15.7071C7.90236 15.3166 7.90236 14.6834 8.29289 14.2929L14.2929 8.29289C14.6834 7.90237 15.3166 7.90237 15.7071 8.29289ZM6.7071 9.29289C7.09763 9.68342 7.09763 10.3166 6.7071 10.7071L5.7071 11.7071C3.88849 13.5257 3.88849 16.4743 5.7071 18.2929C7.52572 20.1115 10.4743 20.1115 12.2929 18.2929L13.2929 17.2929C13.6834 16.9024 14.3166 16.9024 14.7071 17.2929C15.0976 17.6834 15.0976 18.3166 14.7071 18.7071L13.7071 19.7071C11.1074 22.3068 6.89255 22.3068 4.29289 19.7071C1.69322 17.1074 1.69322 12.8926 4.29289 10.2929L5.29289 9.29289C5.68341 8.90237 6.31658 8.90237 6.7071 9.29289Z" fill="currentColor"></path></svg>
                </div>
              </div>
              <div class="w-full text-center text-xs">Copy link</div>
            </button>
            <button id="share-image-twitter" class="relative flex flex-col gap-y-4 disabled:opacity-50 max-sm:gap-y-2">
              <div class="shadow-token-border-default flex h-16 w-16 items-center justify-center rounded-full shadow-md max-sm:h-12 max-sm:w-12">
                <div class="pointer-events-none flex h-8 w-8 items-center justify-center max-sm:h-6 max-sm:w-6">
                  <svg fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
                </div>
              </div>
              <div class="w-full text-center text-xs">X</div>
            </button>
            <button id="share-image-linkedin" class="relative flex flex-col gap-y-4 disabled:opacity-50 max-sm:gap-y-2">
              <div class="shadow-token-border-default flex h-16 w-16 items-center justify-center rounded-full shadow-md max-sm:h-12 max-sm:w-12">
                <div class="pointer-events-none flex h-8 w-8 items-center justify-center max-sm:h-6 max-sm:w-6">
                  <svg fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
                </div>
              </div>
              <div class="w-full text-center text-xs">LinkedIn</div>
            </button>
            <button id="share-image-reddit" class="relative flex flex-col gap-y-4 disabled:opacity-50 max-sm:gap-y-2">
              <div class="shadow-token-border-default flex h-16 w-16 items-center justify-center rounded-full shadow-md max-sm:h-12 max-sm:w-12">
                <div class="pointer-events-none flex h-8 w-8 items-center justify-center max-sm:h-6 max-sm:w-6">
                  <svg fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.249-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.687-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z"/></svg>
                </div>
              </div>
              <div class="w-full text-center text-xs">Reddit</div>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>`;

  const wrapper = document.createElement('div');
  wrapper.id = 'share-image-modal';
  wrapper.className = 'absolute inset-0 max-w-[664px] px-4';
  wrapper.innerHTML = html;
  document.body.appendChild(wrapper);
  addShareImageModalEventListeners(image);
}

/** Simple HTML escape for share modal. */
function escapeHTMLLocal(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * Wire event listeners for the share image modal.
 *
 * Original: content.isolated.end.js line 9934
 */
function addShareImageModalEventListeners(image: GalleryImageNode & { conversation_id?: string }): void {
  const backdrop = document.querySelector('#share-image-modal-content') as HTMLElement;
  const dialog = document.querySelector('#share-image-modal-dialog') as HTMLElement;

  backdrop?.addEventListener('click', (ev) => {
    if (!isDescendant(dialog, ev.target as HTMLElement)) {
      document.querySelector('#share-image-modal')?.remove();
    }
  });

  const closeBtn = document.querySelector('#share-image-close-button');
  const copyLinkBtn = document.querySelector('#share-image-copy-link');
  const twitterBtn = document.querySelector('#share-image-twitter');
  const linkedinBtn = document.querySelector('#share-image-linkedin');
  const redditBtn = document.querySelector('#share-image-reddit');

  const title = image.title || image.prompt || 'Untitled';

  const getPermalink = async (): Promise<string | null> => {
    const data = {
      share_id: image.image_id,
      attachments_to_create: [
        {
          conversation_id: image.conversation_id,
          file_id: image.image_id,
          height: image.height,
          width: image.width,
          kind: 'image_share',
        },
      ],
      post_text: title,
    };
    try {
      const result = await sharePost(data);
      return result?.post?.permalink || null;
    } catch {
      toast('Failed to copy link', 'error');
      return null;
    }
  };

  closeBtn?.addEventListener('click', () => {
    document.querySelector('#share-image-modal')?.remove();
  });

  copyLinkBtn?.addEventListener('click', async () => {
    const link = await getPermalink();
    if (link) {
      await navigator.clipboard.writeText(link);
      toast('Link copied to clipboard', 'success');
    }
  });

  twitterBtn?.addEventListener('click', async () => {
    const link = await getPermalink();
    if (link) window.open(`https://twitter.com/intent/tweet?url=${link}&text=${encodeURIComponent(title)}`, '_blank');
  });

  linkedinBtn?.addEventListener('click', async () => {
    const link = await getPermalink();
    if (link)
      window.open(
        `https://www.linkedin.com/shareArticle?mini=true&url=${link}&text=${encodeURIComponent(title)}`,
        '_blank',
      );
  });

  redditBtn?.addEventListener('click', async () => {
    const link = await getPermalink();
    if (link) window.open(`https://www.reddit.com/submit?url=${link}&title=${encodeURIComponent(title)}`, '_blank');
  });
}
